# Generated by Django 5.2.7 on 2025-10-28 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='users.university'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='users.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
