# Generated by Django 5.2.7 on 2025-10-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_user_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='credits',
        ),
    ]
