# Generated by Django 5.2.7 on 2025-10-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_attendance_window_attendance_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_window',
            old_name='last_actived_by',
            new_name='last_interacted_by',
        ),
    ]
