# Generated by Django 5.2.7 on 2025-10-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_batch_code_batch_university_alter_batch_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='city',
        ),
        migrations.RemoveField(
            model_name='university',
            name='country',
        ),
        migrations.RemoveField(
            model_name='university',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='university',
            name='state',
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
