# Generated by Django 5.2.7 on 2025-10-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_university_city_remove_university_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_years',
        ),
    ]
