# Generated by Django 5.2.7 on 2025-10-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_course_duration_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
