# Generated by Django 5.2.7 on 2025-10-28 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='batch',
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
